pipeline {

    agent any
    
    tools {
        maven 'maven 3.6.1' 
    }
    
    stages {
        stage('Build') {
            steps {
                echo 'Building worker app..'
		dir("worker"){
                	sh 'mvn compile'
		}
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing worker app..'
		dir("worker"){
                	sh 'mvn clean test'
		}
            }
        }
        
        stage('Package') {
            steps {
                echo 'Packaging worker app..'
		dir("worker"){
                	sh 'mvn package -DskipTests'
		}
            }
        }
    }


    post {
        always{
            echo "This is post step..."
        }
    }
}
